Error: Value with name `A` already bound in module
test/analyze/name_resolution/duplicate_toplevels_error/duplicate_toplevels_error.myte:4:9
 4 | import B.A
   |          ^

Error: Value with name `A` already bound in module
test/analyze/name_resolution/duplicate_toplevels_error/duplicate_toplevels_error.myte:5:10
 5 | import C.{A, B, C as B}
   |           ^

Error: Value with name `B` already bound in module
test/analyze/name_resolution/duplicate_toplevels_error/duplicate_toplevels_error.myte:5:21
 5 | import C.{A, B, C as B}
   |                      ^

Error: Value with name `foo` already bound in module
test/analyze/name_resolution/duplicate_toplevels_error/duplicate_toplevels_error.myte:10:4-7
 10 | val foo: int = 1;
    |     ^^^

Error: Value with name `bar` already bound in module
test/analyze/name_resolution/duplicate_toplevels_error/duplicate_toplevels_error.myte:13:4-7
 13 | fun bar() {}
    |     ^^^

Error: Value with name `baz` already bound in module
test/analyze/name_resolution/duplicate_toplevels_error/duplicate_toplevels_error.myte:16:4-7
 16 | val baz: int = 1;
    |     ^^^

Error: Value with name `imported` already bound in module
test/analyze/name_resolution/duplicate_toplevels_error/duplicate_toplevels_error.myte:18:4-12
 18 | fun imported() {}
    |     ^^^^^^^^

Error: Value with name `imported` already bound in module
test/analyze/name_resolution/duplicate_toplevels_error/duplicate_toplevels_error.myte:19:4-12
 19 | val imported: int = 1;
    |     ^^^^^^^^

Error: Type with name `imported` already bound in module
test/analyze/name_resolution/duplicate_toplevels_error/duplicate_toplevels_error.myte:20:11-19
 20 | type alias imported = unit
    |            ^^^^^^^^

Error: Type with name `foo` already bound in module
test/analyze/name_resolution/duplicate_toplevels_error/duplicate_toplevels_error.myte:23:11-14
 23 | type alias foo = int
    |            ^^^