func int @test.main() {
  Call void myte.builtin.exit(1)
  unreachable
}